from enum import Enum

class TrainingJobStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class TrainingAlgorithm(str, Enum):
    LOGISTIC_REGRESSION = "LOGISTIC_REGRESSION"
    RANDOM_FOREST_CLASSIFIER = "RANDOM_FOREST_CLASSIFIER"
    LINEAR_REGRESSION = "LINEAR_REGRESSION"
    RANDOM_FOREST_REGRESSOR = "RANDOM_FOREST_REGRESSOR"

