name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: python -m pytest

      # Docker
      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build CPU image
        if: github.event_name == 'push'
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/modelservemini:${{ github.sha }} \
            -f Dockerfile \
            .

      - name: Push CPU image
        if: github.event_name == 'push'
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/modelservemini:${{ github.sha }}

      - name: Build GPU image
        if: github.event_name == 'push'
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/modelservemini-gpu:${{ github.sha }} \
            -f Dockerfile.gpu \
            .

      - name: Push GPU image
        if: github.event_name == 'push'
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/modelservemini-gpu:${{ github.sha }}


      # apply new docker image version to helm values.yaml
      - name: Checkout deploy repository
        if: github.event_name == 'push'
        uses: actions/checkout@v7
        with:
          repository: homodeus-ms/ModelServeMini-deploy
          token: ${{ secrets.DEPLOY_REPO_TOKEN }}
          path: deploy-repo

      - name: Update deploy image tags
        if: github.event_name == 'push'
        run: |
          yq -i '.image.cpu.tag = "${{ github.sha }}"' deploy-repo/model-serve-mini/values.yaml
          yq -i '.image.gpu.tag = "${{ github.sha }}"' deploy-repo/model-serve-mini/values.yaml

      - name: Commit and push deploy change
        if: github.event_name == 'push'
        shell: bash
        run: |
          cd deploy-repo

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add model-serve-mini/values.yaml
          git commit -m "deploy image ${{ github.sha }}"
          git push